version: '3.8'

services:
  # Frontend development service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: pet-health-frontend-dev
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:5000/api
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - pet-health-network

  # Backend development service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: pet-health-backend-dev
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017/pet-health-dev
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=dev-jwt-secret-key
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./backend/uploads:/app/uploads
    depends_on:
      - mongo
      - redis
    restart: unless-stopped
    networks:
      - pet-health-network

  # MongoDB for development
  mongo:
    image: mongo:6.0
    container_name: pet-health-mongo-dev
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=pet-health-dev
    volumes:
      - mongo_dev_data:/data/db
    restart: unless-stopped
    networks:
      - pet-health-network

  # Redis for development
  redis:
    image: redis:7-alpine
    container_name: pet-health-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    restart: unless-stopped
    networks:
      - pet-health-network

volumes:
  mongo_dev_data:
    driver: local
  redis_dev_data:
    driver: local

networks:
  pet-health-network:
    driver: bridge