apiVersion: apps/v1
kind: Deployment
metadata:
  name: pet-health-backend
  namespace: pet-health
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pet-health-backend
  template:
    metadata:
      labels:
        app: pet-health-backend
    spec:
      containers:
      - name: backend
        image: pet-health-backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: pet-health-config
              key: NODE_ENV
        - name: PORT
          value: "5000"
        - name: MONGODB_URI
          valueFrom:
            configMapKeyRef:
              name: pet-health-config
              key: MONGODB_URI
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: pet-health-config
              key: REDIS_URL
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: pet-health-secrets
              key: JWT_SECRET
        volumeMounts:
        - name: uploads
          mountPath: /app/uploads
        - name: logs
          mountPath: /app/logs
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: uploads
        persistentVolumeClaim:
          claimName: uploads-pvc
      - name: logs
        persistentVolumeClaim:
          claimName: logs-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: pet-health-backend
  namespace: pet-health
spec:
  selector:
    app: pet-health-backend
  ports:
  - port: 5000
    targetPort: 5000

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uploads-pvc
  namespace: pet-health
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-pvc
  namespace: pet-health
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi